### ISSUE TITLE
There is no `vanilla` branch on GitHub

### ISSUE THREAD

**Issue by steveklabnik** [ianfixes/universal_paperclips#1]
> If you want the original game (as of 10/10/17 when I saved the files from my browser), check out the vanilla branch.

https://github.com/ifreecarve/universal_paperclips/branches/all

**Comment by ianfixes** [comment]
Pushed
https://github.com/ifreecarve/universal_paperclips/tree/vanilla

**Comment by steveklabnik** [comment]
Thanks!
